import React, { useState } from "react";
import { 
  Lightbulb, 
  Info, 
  CheckCircle2, 
  TrendingDown, 
  Trees, 
  Globe, 
  Zap, 
  Award,
  ChevronRight,
  Sparkles,
  BookOpen
} from "lucide-react";

// Educational habits with real average yearly CO2 reductions in kg
const EMISSION_HABITS = [
  {
    id: "habit-transit",
    title: "Switch to Transit / Cycle to Work",
    category: "transport",
    description: "Replace daily standard auto commutes with trains, subways, or bike rides.",
    savingKg: 1150,
    emoji: "🚇"
  },
  {
    id: "habit-plant",
    title: "Eco Vegan/Vegetarian Weekdays",
    category: "food",
    description: "Shift to fully plant-based food intake during the week to cut cattle methane metrics.",
    savingKg: 820,
    emoji: "🥗"
  },
  {
    id: "habit-temp",
    title: "Calibrate Home Heating by -1.5°C",
    category: "energy",
    description: "Slightly reduce heating/AC thermostat offsets to save electricity or petroleum indices.",
    savingKg: 340,
    emoji: "🌡️"
  },
  {
    id: "habit-phantom",
    title: "Banish Standby 'Phantom' Sockets",
    category: "energy",
    description: "Power down smart appliances completely or plug into automated toggle strips to halt standby leakage.",
    savingKg: 120,
    emoji: "🔌"
  },
  {
    id: "habit-dryer",
    title: "Air-Dry Wet Laundry Over Hot Dryer",
    category: "energy",
    description: "Use folding clothes-lines or active sun hanging lines to completely bypass rotary driers.",
    savingKg: 210,
    emoji: "☀️"
  },
  {
    id: "habit-compost",
    title: "Active Backyard/Municipal Composting",
    category: "waste",
    description: "Divert household kitchen scraps from landfills where raw organics decay anaerobic methane.",
    savingKg: 150,
    emoji: "🍌"
  },
  {
    id: "habit-thrift",
    title: "Thrift & Pre-Owned Buying Only",
    category: "waste",
    description: "Buy secondary items (apparel, gadgets) to cut initial factory fabrication emissions by half.",
    savingKg: 280,
    emoji: "🧥"
  }
];

// Custom 8-Question Carbon trivia challenge pool (red meat question deleted)
const ALL_TRIVIA_QUESTIONS = [
  {
    id: "q-1",
    question: "Which everyday sector produces the highest share of household carbon emissions globally?",
    options: [
      { key: "A", text: "Streaming movies & cloud computing servers", correct: false },
      { key: "B", text: "Private gasoline car commutes & transport travel", correct: true },
      { key: "C", text: "Plastic household item manufacturing", correct: false },
      { key: "D", text: "Raw wastewater processing lines", correct: false }
    ],
    explanation: "Transport is the leading sector for household emission footprints, contributing over 35% of typical personal emissions due to gasoline internal-combustion vehicles."
  },
  {
    id: "q-3",
    question: "What is 'phantom energy' (or vampire power leakage) in a standard home?",
    options: [
      { key: "A", text: "Electricity drawn by appliances that are plugged in but turned on standby", correct: true },
      { key: "B", text: "Residual static static generated near ceiling fans", correct: false },
      { key: "C", text: "The power lost during solar energy conversion spikes", correct: false },
      { key: "D", text: "Electricity generated by home ground systems", correct: false }
    ],
    explanation: "Unplugging standby electronics (televisual boxes, microwave screens, smart chargers) stops 'phantom load' which accounts for 10% of standard home utility meters."
  },
  {
    id: "q-4",
    question: "Which action yields the HIGHEST standard carbon footprint savings for an individual per year?",
    options: [
      { key: "A", text: "Recycling empty aluminum beverage cans fully", correct: false },
      { key: "B", text: "Replacing all plastic straws with organic bamboo alternatives", correct: false },
      { key: "C", text: "Living car-free or shifting commutes entirely to public transit", correct: true },
      { key: "D", text: "Deleting old emails from your spam folder", correct: false }
    ],
    explanation: "Living car-free or taking trains/bicycles reduces your annual emissions by approximately 1.0 to 2.4 tonnes of CO₂ equivalent — far exceeding material raw plastic swaps."
  },
  {
    id: "q-5",
    question: "What percentage of overall global food production is estimated to be wasted or lost annually?",
    options: [
      { key: "A", text: "Around 5% due to cargo distribution issues", correct: false },
      { key: "B", text: "Approximately 33% (one-third) of all food produced", correct: true },
      { key: "C", text: "Less than 10% because of advanced retail preservatives", correct: false },
      { key: "D", text: "Nearly 60% due to household cooking errors", correct: false }
    ],
    explanation: "Nearly one-third (33%) of all food produced globally goes to landfill waste or is lost during distribution, forming a huge source of global decay emissions."
  },
  {
    id: "q-6",
    question: "Which material requires the most energy to produce from raw materials vs. recycling?",
    options: [
      { key: "A", text: "Glass bottles and jars", correct: false },
      { key: "B", text: "Cardboard shipping containers", correct: false },
      { key: "C", text: "Aluminum cans", correct: true },
      { key: "D", text: "PET plastic beverage packaging", correct: false }
    ],
    explanation: "Recycling aluminum saves 95% of the energy needed to make new aluminum from raw bauxite ore, making it one of the most efficient recycling actions."
  },
  {
    id: "q-7",
    question: "Which of these is the most effective climate benefit of a 'circular economy' framework?",
    options: [
      { key: "A", text: "Ensuring all goods have low-cost worldwide air shipping", correct: false },
      { key: "B", text: "Designing out waste and pollution by keeping materials in continuous loop usage", correct: true },
      { key: "C", text: "Transitioning all power grids exclusively to natural gas", correct: false },
      { key: "D", text: "Allowing plastic items to be burned for indoor space heating", correct: false }
    ],
    explanation: "A circular economy design keeps resources in perpetual reuse, dramatically reducing the raw resource extraction demand and carbon-intensive manufacturing lines."
  },
  {
    id: "q-8",
    question: "How does washing clothes in cold water compare with washing them in hot water?",
    options: [
      { key: "A", text: "Cold water uses about 75% to 90% less energy by avoiding water heating", correct: true },
      { key: "B", text: "It consumes exactly equivalent amounts of electricity", correct: false },
      { key: "C", text: "Cold water actually requires more water volume", correct: false },
      { key: "D", text: "Cold water consumes 30% more motor kinetic power", correct: false }
    ],
    explanation: "About 75-90% of the energy used by a mechanical washing machine goes solely to heating water. Shifting to cold washes dramatically curtails power grids impact."
  },
  {
    id: "q-9",
    question: "Which option represents the cleanest mode of cargo transport per ton of goods shipped?",
    options: [
      { key: "A", text: "Supersonic trans-ocean air freighters", correct: false },
      { key: "B", text: "Ocean container shipping vessels", correct: true },
      { key: "C", text: "Long-haul refrigeration trucks", correct: false },
      { key: "D", text: "High-frequency local cargo vans", correct: false }
    ],
    explanation: "Due to massive cargo volumes, ocean shipping emits far less per ton-mile of transit than any other transport mode, especially air freight or standard trucking grids."
  }
];

const getRandomQuestions = (count: number = 3) => {
  const shuffled = [...ALL_TRIVIA_QUESTIONS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

export default function FootprintAwareness() {
  // 1. Interactive simulated habit togglers state
  const [selectedHabits, setSelectedHabits] = useState<string[]>(["habit-transit", "habit-plant"]);
  
  // Dynamic active questions pool selected on mount or reset
  const [activeQuestions, setActiveQuestions] = useState<typeof ALL_TRIVIA_QUESTIONS>(() => getRandomQuestions(3));

  // 2. Trivia responses state
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [showTriviaFeedback, setShowTriviaFeedback] = useState<Record<string, boolean>>({});

  // Habit selection handler
  const handleToggleHabit = (id: string) => {
    if (selectedHabits.includes(id)) {
      setSelectedHabits(selectedHabits.filter(h => h !== id));
    } else {
      setSelectedHabits([...selectedHabits, id]);
    }
  };

  // Calculate annual savings
  const totalAnnualSavings = EMISSION_HABITS
    .filter(h => selectedHabits.includes(h.id))
    .reduce((sum, h) => sum + h.savingKg, 0);

  // Equivalencies
  const treesPlantedEquiv = Math.round(totalAnnualSavings / 22); // A mature tree absorbs 22kg/year
  const carMilesAvoided = Math.round(totalAnnualSavings * 2.5); // avg 0.4kg per mile

  // Trivia handler
  const handleSelectAnswer = (qId: string, optionKey: string) => {
    setAnswers({ ...answers, [qId]: optionKey });
    setShowTriviaFeedback({ ...showTriviaFeedback, [qId]: true });
  };

  // Count correct quiz answers
  const correctCount = activeQuestions.reduce((count, q) => {
    const selectedOpt = q.options.find(o => o.key === answers[q.id]);
    return count + (selectedOpt && selectedOpt.correct ? 1 : 0);
  }, 0);

  const isQuizComplete = activeQuestions.length > 0 && Object.keys(answers).length === activeQuestions.length;


  return (
    <div className="space-y-6" id="footprint-awareness-root">
      
      {/* 1. INTRO HERO BANNER */}
      <div 
        className="p-6 md:p-8 rounded-[2.5rem] bg-neutral-950 text-white border-2 border-zinc-950 overflow-hidden relative shadow-sm"
        id="reduce-footprint-hero"
      >
        {/* Subtle ambient lighting */}
        <div className="absolute right-[-30px] top-[-30px] w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute left-[-40px] bottom-[-40px] w-48 h-48 bg-teal-500/10 rounded-full blur-2xl pointer-events-none" />

        <div className="relative z-10 space-y-3">
          <span className="px-3 py-1 bg-emerald-500/20 text-emerald-400 text-[9px] font-mono font-black rounded-lg uppercase tracking-wider border border-emerald-500/20 flex items-center gap-1.5 w-fit">
            <BookOpen className="w-3.5 h-3.5" /> EMISSION REDUCTION ACADEMY
          </span>
          <h2 className="text-2xl md:text-3xl font-black italic uppercase text-zinc-50 font-sans tracking-tight leading-none">
            Master Your Carbon <span className="text-emerald-400">Impact Blueprint</span>
          </h2>
          <p className="text-xs md:text-sm text-zinc-400 max-w-2xl leading-relaxed font-semibold">
            Did you know a single average global citizen contributes <span className="text-zinc-100 font-extrabold underline">4,700 kg of CO₂ annually</span>? 
            To bypass climate tipping points, our shared baseline needs to drop under <span className="text-emerald-400 font-extrabold">2,000 kg per year</span>. 
            Review immediate habits below to construct your personal savings playbook.
          </p>
        </div>
      </div>

      {/* 2. DYNAMIC INTERACTIVE HABIT TOGGLE PLAYBOOK SIMULATOR */}
      <div 
        className="bg-white border-2 border-zinc-200 rounded-[2.5rem] p-6 md:p-8 shadow-sm space-y-6"
        id="active-habit-simulator-section"
      >
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-zinc-150">
          <div className="space-y-1">
            <span className="px-2.5 py-1 bg-amber-50 text-amber-800 text-[10px] font-mono font-bold rounded-lg uppercase tracking-wider border border-amber-200 flex items-center gap-1.5 w-fit">
              <Lightbulb className="w-3 h-3 text-amber-500 fill-amber-500" /> LIVE PROJECTOR
            </span>
            <h3 className="text-lg md:text-xl font-black text-zinc-900 uppercase italic">
              Interactive Habit <span className="text-emerald-700">Projector & Commitments</span>
            </h3>
            <p className="text-xs text-zinc-550 leading-relaxed font-semibold">
              Toggle sustainable actions below to instantly forecast your yearly carbon metric offset. Commit to what works for you!
            </p>
          </div>

          {/* Dynamic real-time calculated counter */}
          <div className="p-4 rounded-2xl bg-zinc-900 text-white text-center uppercase shrink-0 sm:min-w-[180px] shadow-sm relative overflow-hidden">
            <span className="text-[9px] text-zinc-400 block font-bold tracking-wider relative z-10">Simulated Yearly Offset</span>
            <span className="text-2xl md:text-3xl font-mono font-black text-emerald-400 block mt-0.5 relative z-10">-{totalAnnualSavings} kg</span>
            <span className="text-[8px] text-zinc-500 block font-mono font-bold tracking-wider mt-0.5 relative z-10">
              {selectedHabits.length} of {EMISSION_HABITS.length} Habits Committed
            </span>
          </div>
        </div>

        {/* Dynamic environmental context boxes */}
        {totalAnnualSavings > 0 && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4" id="simulated-offsets-equivalencies">
            <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-2xl flex items-center gap-3.5">
              <div className="p-3 bg-emerald-600 teXT-white rounded-xl text-xl shrink-0">
                🌲
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-emerald-800 tracking-wider block">Trees Absorbing for You</span>
                <span className="text-xl font-black text-emerald-950 block mt-0.5">{treesPlantedEquiv} mature trees</span>
                <p className="text-[10px] text-emerald-700 font-semibold leading-normal mt-0.5">Equivalent to planting these to mitigate carbon indices.</p>
              </div>
            </div>

            <div className="p-4 bg-teal-50 border border-teal-200 rounded-2xl flex items-center gap-3.5">
              <div className="p-3 bg-teal-600 text-white rounded-xl text-xl shrink-0">
                🚗
              </div>
              <div>
                <span className="text-[10px] uppercase font-bold text-teal-800 tracking-wider block">Equivalent Commuting Offset</span>
                <span className="text-xl font-black text-teal-950 block mt-0.5">{carMilesAvoided} ICE miles avoided</span>
                <p className="text-[10px] text-teal-700 font-semibold leading-normal mt-0.5">Equivalent gasoline driving mileage cancelled entirely!</p>
              </div>
            </div>
          </div>
        )}

        {/* Interactive list grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2" id="simulated-habits-toggles-grid">
          {EMISSION_HABITS.map((habit) => {
            const isCommitted = selectedHabits.includes(habit.id);
            return (
              <div
                key={habit.id}
                onClick={() => handleToggleHabit(habit.id)}
                className={`p-4 rounded-2xl border-2 transition cursor-pointer select-none relative overflow-hidden flex flex-col justify-between space-y-3 ${
                  isCommitted
                    ? "bg-emerald-500/[0.04] border-emerald-500 shadow-[0_4px_12px_rgba(16,185,129,0.04)]"
                    : "bg-white border-zinc-150 hover:border-zinc-250 hover:bg-zinc-50/50"
                }`}
              >
                {/* Committed Checkmark */}
                {isCommitted && (
                  <div className="absolute right-3.5 top-3.5">
                    <CheckCircle2 className="w-5 h-5 text-emerald-600 fill-emerald-500/10" />
                  </div>
                )}

                <div className="pr-8 space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-lg select-none">{habit.emoji}</span>
                    <h4 className="text-xs font-black text-zinc-900 uppercase">{habit.title}</h4>
                  </div>
                  <p className="text-[11px] text-zinc-500 leading-normal font-semibold">
                    {habit.description}
                  </p>
                </div>

                <div className="flex items-center justify-between pt-1 border-t border-zinc-100 mt-2.5">
                  <span className={`text-[10px] uppercase font-mono font-bold px-2 py-0.5 rounded-md ${
                    isCommitted ? "bg-emerald-100 text-emerald-800" : "bg-zinc-100 text-zinc-500"
                  }`}>
                    {habit.category}
                  </span>
                  <span className="text-xs font-mono font-black text-zinc-900">
                    -{habit.savingKg} kg CO₂ / year
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* 3. INTERACTIVE CARBON TRIVIA QUEST CHALLENGE */}
      <div 
        className="bg-white border-2 border-zinc-200 rounded-[2.5rem] p-6 md:p-8 shadow-sm space-y-6"
        id="trivia-quiz-interactive-section"
      >
        <div className="pb-4 border-b border-zinc-150 space-y-1">
          <span className="px-2.5 py-1 bg-purple-50 text-purple-800 text-[10px] font-mono font-bold rounded-lg uppercase tracking-wider border border-purple-200 flex items-center gap-1.5 w-fit">
            <Sparkles className="w-3 h-3 text-purple-500" /> KNOWLEDGE SNAPSHOT
          </span>
          <h3 className="text-lg md:text-xl font-black text-zinc-900 uppercase italic">
            Interactive Carbon <span className="text-purple-700">Trivia Quest</span>
          </h3>
          <p className="text-xs text-zinc-550 leading-relaxed font-semibold">
            Test your understanding about emission drivers and circular economies on this fully client-side trivia simulator.
          </p>
        </div>

        {/* Trivia Quest Render List */}
        <div className="space-y-6 pt-2" id="carbon-quiz-questions-list">
          {activeQuestions.map((q, qIndex) => {
            const hasAnswered = showTriviaFeedback[q.id];
            const chosenKey = answers[q.id];

            return (
              <div 
                key={q.id} 
                className="p-5 rounded-2xl bg-zinc-50 border border-zinc-200 space-y-3.5 relative"
                id={`trivia-box-container-${q.id}`}
              >
                {/* Question index */}
                <span className="absolute right-4 top-4 text-[10px] font-mono font-bold text-zinc-400">
                  Question 0{qIndex + 1}
                </span>

                <h4 className="text-xs md:text-sm font-black text-zinc-900 leading-snug pr-12">
                  {q.question}
                </h4>

                {/* Grid Options buttons */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2" id={`options-grid-${q.id}`}>
                  {q.options.map((option) => {
                    const isChosen = chosenKey === option.key;
                    const isCorrect = option.correct;
                    
                    let buttonStyle = "bg-white border-zinc-200 text-zinc-800 hover:bg-zinc-100 hover:border-zinc-300";
                    
                    if (hasAnswered) {
                      if (isCorrect) {
                        buttonStyle = "bg-emerald-500/10 border-emerald-500 text-emerald-950 font-bold shadow-sm";
                      } else if (isChosen && !isCorrect) {
                        buttonStyle = "bg-red-500/10 border-red-500 text-red-950 font-bold";
                      } else {
                        buttonStyle = "bg-white border-zinc-200 text-zinc-450 opacity-60";
                      }
                    } else if (isChosen) {
                      buttonStyle = "bg-purple-500/10 border-purple-500 text-purple-950 font-bold";
                    }

                    return (
                      <button
                        key={option.key}
                        disabled={hasAnswered}
                        onClick={() => handleSelectAnswer(q.id, option.key)}
                        className={`text-left p-3 rounded-xl border text-[11px] md:text-xs transition flex gap-2 w-full font-semibold items-start cursor-pointer select-none ${buttonStyle}`}
                      >
                        <span className="font-mono text-[10px] px-1 bg-zinc-100 rounded text-zinc-500 mt-0.5 shrink-0">
                          {option.key}
                        </span>
                        <span>{option.text}</span>
                      </button>
                    );
                  })}
                </div>

                {/* Explanation text box */}
                {hasAnswered && (
                  <div className="p-3.5 bg-zinc-100 rounded-xl text-[10px] md:text-[11px] leading-relaxed text-zinc-650 flex gap-2 justify-start items-start border border-zinc-200">
                    <Info className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                    <div>
                      <span className="font-extrabold text-zinc-800 uppercase text-[9px] tracking-wider block mb-0.5">
                        {q.options.find(o => o.key === chosenKey)?.correct ? "✓ Correct Answer!" : "✗ Incorrect Selection"}
                      </span>
                      {q.explanation}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Dynamic Final Trophy award overlay based on quiz score results */}
        {isQuizComplete && (
          <div 
            className="p-5 rounded-3xl bg-neutral-950 text-white flex flex-col sm:flex-row items-center justify-between gap-4 shadow-md relative overflow-hidden"
            id="trivia-quiz-outcome-card"
          >
            <div className="absolute right-[-20px] top-[-20px] opacity-10">
              <Award className="w-32 h-32 text-purple-500" />
            </div>

            <div className="flex items-center gap-3.5 relative z-10 text-center sm:text-left">
              <div className="p-3.5 bg-purple-500 text-white rounded-2xl text-2xl shrink-0">
                🏆
              </div>
              <div>
                <h4 className="text-xs font-black uppercase text-purple-400 tracking-wider">Trivia Quest Calculated Results</h4>
                <span className="text-base md:text-lg font-black text-white block mt-0.5">
                  You scored {correctCount} out of {activeQuestions.length} Correct Answers!
                </span>
                <p className="text-[10px] text-zinc-400 mt-1 max-w-md leading-normal font-semibold">
                  {correctCount === activeQuestions.length 
                    ? "Absolute Climate Brains! You fully understand the physics of carbon and sustainable actions!" 
                    : "Great effort! Review the incorrect answers above to grasp daily eco-rebalancing techniques."}
                </p>
              </div>
            </div>

            <button
              onClick={() => {
                setAnswers({});
                setShowTriviaFeedback({});
                setActiveQuestions(getRandomQuestions(3));
              }}
              className="py-2.5 px-5 rounded-xl bg-purple-500 hover:bg-purple-400 text-neutral-950 font-mono text-[10px] font-black uppercase tracking-wider transition active:scale-95 cursor-pointer shrink-0 z-10 shadow border border-purple-400"
            >
              Reset Quiz Trivia
            </button>
          </div>
        )}
      </div>

    </div>
  );
}
